### ISSUE TITLE
Feedback in terminal 

### ISSUE THREAD

**Issue by albertcito** [ElMassimo/vite-plugin-bugsnag#3]
### Description
- Add option `feedback` as boolean
 
**Describe the solution you'd like**
- If `feedback` is true, then display in terminal something like:
   - Uploading source map ⬆️
   - Source map upload ✅

**Additional context**
It will be great to know what is doing the process.

**Comment by albertcito** [comment]
I just see [BuildReporterConfig](https://github.com/ElMassimo/vite-plugin-bugsnag/blob/main/src/types.ts#L61) has the option to set the `logLevel`

`logLevel: 'debug'`

**Comment by jdferreira-biai** [comment]
There is no 'logLevel' option in the [SourceMapUploaderConfig](https://github.com/ElMassimo/vite-plugin-bugsnag/blob/main/src/types.ts#L97). ☹️
